### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by jkbest2** [ElOceanografo/SPDEPrecisionMatrices.jl#1]
I think SparseSpatialPrecisionMatrices.jl is fine, but might be too specific. Using the SPDE method in one dimension is straightforward, and three dimensions either via a three-dimensional mesh or using a separable temporal effect (e.g. a one-dimensional mesh) is also doable. I'd propose your original SPDEPrecisionMatrices.jl, or something a bit more specific like MaternSPDEPrecisionMatrices.jl. Might be worth mentioning something to the DIffEq folks to make sure we're not stepping on any toes.

**Comment by ElOceanografo** [comment]
I guess it depends somewhat on what the scope of this package ends up being, i.e. whether it's just a backend implementing the SPDE method or evolves into something more full-featured...see my brainstorming in #3.

**Comment by ElOceanografo** [comment]
Decided to rename to `SPDEPrecisionMatrices` before we get used to the old one. @jkbest2 you may want to delete and re-add the package.
